### ISSUE TITLE
Store actual PDF files

### ISSUE THREAD

**Issue by p16i** [PyThaiNLP/thai-covid-19-situation#1]
I've recently read a FB post, telling there some daily reports changed by the ministry. IMHO, it should not be that way. Having the actual files will allow us to compare.

it might be good to somehow submit those files (links) to http://web.archive.org.

**Comment by wannaphong** [comment]
I agree. I write auto archive pdf scripts and I used Travis CI for run auto archive pdf scripts.

Code https://github.com/PyThaiNLP/thai-covid-19-situation/blob/master/savepdf.py

**Comment by p16i** [comment]
Sounds good! You might want to try GitHub Action. Somehow, I like it more than Travis.

**Comment by wannaphong** [comment]
@heytitle OK. I moved it to GitHub Action. https://github.com/PyThaiNLP/thai-covid-19-situation/actions
